# Generated by Django 6.1 on 2026-08-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_page_alter_sitesettings_site_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainpage',
            options={'verbose_name': 'Головна сторінка', 'verbose_name_plural': 'Головна сторінка'},
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='title',
            field=models.CharField(default='TRADING 2D', max_length=255),
        ),
    ]
