# Generated by Django 6.1 on 2026-08-26 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_mainpage_options_alter_mainpage_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactpage',
            options={'verbose_name': 'Сторінка контактів', 'verbose_name_plural': 'Контакти'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Інформаційна сторінка', 'verbose_name_plural': 'Інформаційні сторінки'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Налаштування сайту', 'verbose_name_plural': 'Налаштування сайту'},
        ),
    ]
