# Generated by Django 6.1 on 2026-08-27 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_meta_description_product_meta_title_and_more'),
        ('website', '0007_mainpage_hero_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='Пошук — за назвою товару. Якщо не обрано, підбирається автоматично з хітів/новинок.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products.gallery', verbose_name='Фото товару для банера'),
        ),
    ]
