# Generated by Django 6.1 on 2026-09-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_mainpage_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='address_en',
            field=models.TextField(blank=True, verbose_name='Адреса (EN)'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='address_ru',
            field=models.TextField(blank=True, verbose_name='Адреса (RU)'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Опис (EN)'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Опис (RU)'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок (EN)'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок (RU)'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Опис (EN)'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Опис (RU)'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок (EN)'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок (RU)'),
        ),
        migrations.AddField(
            model_name='page',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Опис (EN)'),
        ),
        migrations.AddField(
            model_name='page',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Опис (RU)'),
        ),
        migrations.AddField(
            model_name='page',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок (EN)'),
        ),
        migrations.AddField(
            model_name='page',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок (RU)'),
        ),
    ]
