# Generated by Django 6.1 on 2026-08-26 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_slug_sku_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренди',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Зовнішній ID (з фіда постачальника)'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='source_url',
            field=models.URLField(blank=True, verbose_name='Посилання на оригінал'),
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=64, verbose_name='Штрихкод (EAN)'),
        ),
        migrations.AddField(
            model_name='product',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Зовнішній ID (з фіда постачальника)'),
        ),
        migrations.AddField(
            model_name='product',
            name='source_url',
            field=models.URLField(blank=True, verbose_name='Посилання на оригінал'),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor_code',
            field=models.CharField(blank=True, max_length=128, verbose_name='Код виробника'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.brand', verbose_name='Бренд'),
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва характеристики')),
                ('value', models.CharField(max_length=500, verbose_name='Значення')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='products.product')),
            ],
            options={
                'verbose_name': 'Характеристика товару',
                'verbose_name_plural': 'Характеристики товару',
                'ordering': ['order', 'pk'],
            },
        ),
    ]
