# Generated by Django 6.1 on 2026-08-26 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_category_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категорія', 'verbose_name_plural': 'Категорії'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Зображення', 'verbose_name_plural': 'Галерея'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товари'},
        ),
    ]
