# Generated by Django 6.1 on 2026-09-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_meta_description_product_meta_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Опис (EN)'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Опис (RU)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Назва (EN)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Назва (RU)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Опис (EN)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Опис (RU)'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description_en',
            field=models.CharField(blank=True, max_length=320, verbose_name='SEO: опис (EN)'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description_ru',
            field=models.CharField(blank=True, max_length=320, verbose_name='SEO: опис (RU)'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='SEO: заголовок (EN)'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='SEO: заголовок (RU)'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Назва (EN)'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Назва (RU)'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Назва (EN)'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Назва (RU)'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='value_en',
            field=models.CharField(blank=True, max_length=500, verbose_name='Значення (EN)'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='value_ru',
            field=models.CharField(blank=True, max_length=500, verbose_name='Значення (RU)'),
        ),
    ]
