# Generated by Django 6.1 on 2026-08-26 13:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0007_admin_verbose_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('new', 'Нове'), ('confirmed', 'Підтверджено'), ('paid', 'Оплачено'), ('shipped', 'Відправлено'), ('done', 'Завершено'), ('cancelled', 'Скасовано')], default='new', max_length=16)),
                ('full_name', models.CharField(max_length=255, verbose_name='ПІБ')),
                ('phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('comment', models.TextField(blank=True, verbose_name='Коментар до замовлення')),
                ('delivery_method', models.CharField(choices=[('np_warehouse', 'Нова Пошта — відділення'), ('np_courier', 'Нова Пошта — курʼєр'), ('self_pickup', 'Самовивіз')], max_length=16)),
                ('np_city_name', models.CharField(blank=True, max_length=255, verbose_name='Місто (Нова Пошта)')),
                ('np_city_ref', models.CharField(blank=True, max_length=64)),
                ('np_warehouse_name', models.CharField(blank=True, max_length=255, verbose_name='Відділення (Нова Пошта)')),
                ('np_warehouse_ref', models.CharField(blank=True, max_length=64)),
                ('payment_method', models.CharField(choices=[('liqpay', 'Оплата картою онлайн (LiqPay)'), ('cod', 'Оплата при отриманні')], max_length=16)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_transaction_id', models.CharField(blank=True, max_length=128)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order_number'], name='orders_orde_order_n_f3ada5_idx'), models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_sku', models.CharField(blank=True, max_length=64)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.product')),
            ],
            options={
                'verbose_name': 'Позиція замовлення',
                'verbose_name_plural': 'Позиції замовлення',
            },
        ),
    ]
